/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadordeestoque;

import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.Converter;

/**
 *
 * @author guilhermeantonelli
 */
public class GerenciadorV extends javax.swing.JFrame {

    /**
     * Creates new form GerenciadorV
     */
    public GerenciadorV() {
        initComponents();
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        idRemover = new javax.swing.JTextField();
        btnRemover = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomeEletro = new javax.swing.JTextField();
        fabEletro = new javax.swing.JTextField();
        qtdEletro = new javax.swing.JSpinner();
        ValEletro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        classEf = new javax.swing.JTextField();
        potenc = new javax.swing.JTextField();
        volt = new javax.swing.JTextField();
        novoEletronico = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nomePere = new javax.swing.JTextField();
        fabPere = new javax.swing.JTextField();
        qtdPere = new javax.swing.JSpinner();
        valPere = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        validadePer = new javax.swing.JTextField();
        novoPerecivel = new javax.swing.JButton();
        refrig = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        nomeMovel = new javax.swing.JTextField();
        fabMovel = new javax.swing.JTextField();
        qtdMovel = new javax.swing.JSpinner();
        valMovel = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tpMaterial = new javax.swing.JTextField();
        novoMovel = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        cor = new javax.swing.JTextField();
        btnMostrarTodos = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProdutos = new javax.swing.JTextArea();
        buscarID = new javax.swing.JTextField();
        btnBuscarId = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        addEletronico = new javax.swing.JMenuItem();
        addPerecivel = new javax.swing.JMenuItem();
        addMovel = new javax.swing.JMenuItem();
        removerPorId = new javax.swing.JMenu();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Controle de estroque");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel5.setInheritsPopupMenu(true);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setText("ID Produto");
        jLabel20.setAutoscrolls(true);
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 18, -1, -1));
        jPanel5.add(idRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 40, 81, -1));

        btnRemover.setText("Remover");
        btnRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoverMouseClicked(evt);
            }
        });
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel5.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 40, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nome");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 21, -1, -1));

        jLabel3.setText("Fabricante");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 81, -1, -1));

        jLabel5.setText("Valor unitario");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 264, -1, -1));

        jLabel6.setText("Quantidade");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 264, -1, -1));
        jPanel2.add(nomeEletro, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 43, 338, -1));
        jPanel2.add(fabEletro, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 109, 338, -1));
        jPanel2.add(qtdEletro, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 259, -1, -1));
        jPanel2.add(ValEletro, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 259, 77, -1));

        jLabel4.setText("Voltagem");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 166, -1, -1));

        jLabel7.setText("Potencia");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 166, -1, -1));

        jLabel8.setText("Classe Eficiencia");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 210, -1, -1));
        jPanel2.add(classEf, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 205, 92, -1));
        jPanel2.add(potenc, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 161, 92, -1));
        jPanel2.add(volt, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 161, 92, -1));

        novoEletronico.setText("Adicionar");
        novoEletronico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novoEletronicoMouseClicked(evt);
            }
        });
        novoEletronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoEletronicoActionPerformed(evt);
            }
        });
        jPanel2.add(novoEletronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 276, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Nome");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 21, -1, -1));

        jLabel10.setText("Fabricante");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 81, -1, -1));

        jLabel11.setText("Valor unitario");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 264, -1, -1));

        jLabel12.setText("Quantidade");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 264, -1, -1));
        jPanel3.add(nomePere, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 43, 338, -1));
        jPanel3.add(fabPere, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 109, 338, -1));
        jPanel3.add(qtdPere, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 259, -1, -1));
        jPanel3.add(valPere, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 259, 77, -1));

        jLabel13.setText("Validade");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 166, -1, -1));
        jPanel3.add(validadePer, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 161, 92, -1));

        novoPerecivel.setText("Adicionar");
        novoPerecivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novoPerecivelMouseClicked(evt);
            }
        });
        novoPerecivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoPerecivelActionPerformed(evt);
            }
        });
        jPanel3.add(novoPerecivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 276, -1, -1));

        refrig.setText("Refrigerado");
        jPanel3.add(refrig, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 162, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Nome");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 21, -1, -1));

        jLabel15.setText("Fabricante");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 81, -1, -1));

        jLabel16.setText("Valor unitario");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 264, -1, -1));

        jLabel17.setText("Quantidade");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 264, -1, -1));
        jPanel4.add(nomeMovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 43, 338, -1));
        jPanel4.add(fabMovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 109, 338, -1));
        jPanel4.add(qtdMovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 259, -1, -1));
        jPanel4.add(valMovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 259, 77, -1));

        jLabel18.setText("Tipo Material");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 147, -1, -1));
        jPanel4.add(tpMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 172, 338, -1));

        novoMovel.setText("Adicionar");
        novoMovel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novoMovelMouseClicked(evt);
            }
        });
        novoMovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoMovelActionPerformed(evt);
            }
        });
        jPanel4.add(novoMovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 276, -1, -1));

        jLabel19.setText("Cor");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 204, -1, -1));

        cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corActionPerformed(evt);
            }
        });
        jPanel4.add(cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 226, 338, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnMostrarTodos.setText("Todos");
        btnMostrarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarTodosMouseClicked(evt);
            }
        });
        btnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 114, -1));

        jButton4.setText("Movel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 114, -1));

        jButton5.setText("Eletronicos");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 114, -1));

        listaProdutos.setEditable(false);
        listaProdutos.setColumns(20);
        listaProdutos.setRows(5);
        jScrollPane1.setViewportView(listaProdutos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 600, 352));

        buscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIDActionPerformed(evt);
            }
        });
        jPanel1.add(buscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 114, -1));

        btnBuscarId.setText("Buscar ID");
        btnBuscarId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarIdMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        jButton6.setText("Perecivel");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 114, -1));

        jLayeredPane2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 739, -1));

        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 51));

        jMenu3.setBackground(new java.awt.Color(255, 255, 51));
        jMenu3.setText("Adicionar Produto");

        addEletronico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        addEletronico.setText("Eletronico");
        addEletronico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEletronicoMouseClicked(evt);
            }
        });
        addEletronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEletronicoActionPerformed(evt);
            }
        });
        jMenu3.add(addEletronico);

        addPerecivel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        addPerecivel.setText("Perecivel");
        addPerecivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPerecivelActionPerformed(evt);
            }
        });
        jMenu3.add(addPerecivel);

        addMovel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        addMovel.setText("Movel");
        addMovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovelActionPerformed(evt);
            }
        });
        jMenu3.add(addMovel);

        jMenuBar1.add(jMenu3);

        removerPorId.setText(" Remover Produto");
        removerPorId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removerPorIdMouseClicked(evt);
            }
        });
        removerPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerPorIdActionPerformed(evt);
            }
        });
        jMenuBar1.add(removerPorId);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEletronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEletronicoActionPerformed
        jPanel2.setVisible(true);
    }//GEN-LAST:event_addEletronicoActionPerformed

    private void addEletronicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEletronicoMouseClicked
       
    }//GEN-LAST:event_addEletronicoMouseClicked

    private void novoEletronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoEletronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoEletronicoActionPerformed

    private void novoEletronicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novoEletronicoMouseClicked
        try{
            produtos.adicionar(new Eletronico(nomeEletro.getText(), fabEletro.getText(), produtos.produtos.size() > 0 ? (produtos.produtos.get(produtos.produtos.size() -1).getCodigo() + 1) : 1, Float.parseFloat(ValEletro.getText()), (int)qtdEletro.getValue(), volt.getText(), Integer.parseInt(potenc.getText()), classEf.getText().toCharArray()[0]));
            JOptionPane.showMessageDialog(null, "Produto cadastrado");
            jPanel2.setVisible(false);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar o produto");
        }
    }//GEN-LAST:event_novoEletronicoMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed

    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void btnMostrarTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarTodosMouseClicked
        listaProdutos.setText(produtos.listarPerecivel() + "" + produtos.listarMovel()+ "" + produtos.listarEletronicos());
    }//GEN-LAST:event_btnMostrarTodosMouseClicked

    private void novoPerecivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novoPerecivelMouseClicked
         try{
            produtos.adicionar(new Perecivel(nomePere.getText(), fabPere.getText(), produtos.produtos.size() > 0 ? (produtos.produtos.get(produtos.produtos.size() -1).getCodigo() + 1) : 1, Float.parseFloat(valPere.getText()), (int)qtdPere.getValue(), validadePer.getText(), refrig.isSelected()));
            JOptionPane.showMessageDialog(null, "Produto cadastrado");
            jPanel3.setVisible(false);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar o produto");
        }
    }//GEN-LAST:event_novoPerecivelMouseClicked

    private void novoPerecivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoPerecivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoPerecivelActionPerformed

    private void addPerecivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPerecivelActionPerformed
       jPanel3.setVisible(true);
    }//GEN-LAST:event_addPerecivelActionPerformed

    private void novoMovelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novoMovelMouseClicked
          try{
            produtos.adicionar(new Movel(nomeMovel.getText(), fabMovel.getText(), produtos.produtos.size() > 0 ? (produtos.produtos.get(produtos.produtos.size() -1).getCodigo() + 1) : 1, Float.parseFloat(valMovel.getText()), (int)qtdMovel.getValue(), tpMaterial.getText(), cor.getText()));
            JOptionPane.showMessageDialog(null, "Produto cadastrado");
            jPanel4.setVisible(false);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar o produto");
        }
    }//GEN-LAST:event_novoMovelMouseClicked

    private void novoMovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoMovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoMovelActionPerformed

    private void corActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corActionPerformed

    private void addMovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovelActionPerformed
        jPanel4.setVisible(true);
    }//GEN-LAST:event_addMovelActionPerformed

    private void buscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarIDActionPerformed

    private void btnBuscarIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarIdMouseClicked
        try{
        listaProdutos.setText(produtos.buscarPorCodigo(Integer.parseInt(buscarID.getText())).imprimir());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Produto não encontrado!");
        }
    }//GEN-LAST:event_btnBuscarIdMouseClicked

    private void removerPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerPorIdActionPerformed
        jPanel5.setVisible(true);
    }//GEN-LAST:event_removerPorIdActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseClicked
        try{
        produtos.remover(Integer.parseInt(idRemover.getText()));
        jPanel5.setVisible(false);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Produto não encontrado!");
            jPanel5.setVisible(false);
        }
    }//GEN-LAST:event_btnRemoverMouseClicked

    private void removerPorIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerPorIdMouseClicked
        jPanel5.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_removerPorIdMouseClicked

GerenciarProduto produtos = new GerenciarProduto();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciadorV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciadorV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciadorV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciadorV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciadorV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ValEletro;
    private javax.swing.JMenuItem addEletronico;
    private javax.swing.JMenuItem addMovel;
    private javax.swing.JMenuItem addPerecivel;
    private javax.swing.JButton btnBuscarId;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnRemover;
    private javax.swing.JTextField buscarID;
    private javax.swing.JTextField classEf;
    private javax.swing.JTextField cor;
    private javax.swing.JTextField fabEletro;
    private javax.swing.JTextField fabMovel;
    private javax.swing.JTextField fabPere;
    private javax.swing.JTextField idRemover;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listaProdutos;
    private javax.swing.JTextField nomeEletro;
    private javax.swing.JTextField nomeMovel;
    private javax.swing.JTextField nomePere;
    private javax.swing.JButton novoEletronico;
    private javax.swing.JButton novoMovel;
    private javax.swing.JButton novoPerecivel;
    private javax.swing.JTextField potenc;
    private javax.swing.JSpinner qtdEletro;
    private javax.swing.JSpinner qtdMovel;
    private javax.swing.JSpinner qtdPere;
    private javax.swing.JCheckBox refrig;
    private javax.swing.JMenu removerPorId;
    private javax.swing.JTextField tpMaterial;
    private javax.swing.JTextField valMovel;
    private javax.swing.JTextField valPere;
    private javax.swing.JTextField validadePer;
    private javax.swing.JTextField volt;
    // End of variables declaration//GEN-END:variables
}
